//planting
const PLANTING_OPACITY_STEPS = 4
const PLANTING_DROP_BEAN_STEPS = 6
const PLANTING_ROTATE_HAND_STEPS = 5
const PLANTING_PHASE_STEPS = 3
const PLANTING_HAND_MAX_ROTATE = 50
const PLANTING_SECTION_STEPS = 31


//growing
const GROWING_FIRST_MOUNTAINS = 4
const GROWING_SECOND_MOUNTAINS = 4
const GROWING_TROPIC_TEXT = 4
const GROWING_SUBTROPIC_TEXT = 4
const GROWING_ROBUSTA_STEPS = 8
const GROWING_ARABICA_STEPS = 8
const GROWING_ROBUSTA_MAX_BOTTOM = 240
const GROWING_ARABICA_MAX_BOTTOM = 420
const GROWING_SECTION_STEPS = 9

const STEP_SIZE = 100